databases:
  - name: demoapp
    databaseName: demoapp
    user: demoapp
    plan: free

services:
  - type: web
    plan: free
    name: demoapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: demoapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
